
name: Test Manual Workflow

on:
  workflow_dispatch:

inputs:
  test_message:
    description: "The test message"
    required: true
    default: "Yoh!"

jobs:
  do_stuff:
    runs-on: ubuntu-latest

    steps:
      - name: Displays test message
        run: echo $INPUT_TEST_MESSAGE

